pria(x,bahrun).
pria(bahrun,fahri).
perempuan(fahri,salsa).
pria(fahri,arfan).
perempuan(bahrun,salma).
pria(salma,farhan).
perempuan(x,farah).
pria(farah,ferdi).
perempuan(ferdi,syifa).
pria(ferdi,faiz).
pria(farah,burhan).